name: create-image

on:
  push:
    branches: [ main ]
    
permissions:
  packages: write
  contents: read
  
jobs: 
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log into Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./KProject.Api/Dockerfile
          push: true
          build-args: BUILD_CONFIGURATION=Release
          tags: |
            ghcr.io/wilasj/kproject:latest
            ghcr.io/wilasj/kproject:${{ github.sha }}
            
      - name: Trigger Dokploy
        run: |
          curl -X POST "${{secrets.DOKPLOY_API_URL}}" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: ${{secrets.DOKPLOY_API_TOKEN}}' \
          -d '{
            "composeId": "${{ secrets.DOKPLOY_APPLICATION_ID }}"
          }'